# -*- mode: ruby -*-
# vi: set ft=ruby :

# ref_url: https://github.com/DevNIX/Vagrant-dependency-manager
require File.dirname(__FILE__)+"/vagrant_customizations/dependency_manager"
check_plugins ["vagrant-docker-compose", "vagrant-awsinfo", "vagrant-docker-login", "vagrant-aws", "vagrant-share", "vagrant-winrm-syncedfolders"]

require 'yaml'
asset = YAML.load_file("./yaml/aws.yaml")
nodes = YAML.load_file("./yaml/vagrant.yaml")

Vagrant.configure("2") do |config|
  config.vm.box = "dummy"
  config.vm.box_url = "https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box"

  nodes.each do |node|
    config.vm.define node["name"] do |node_config|
      node_config.vm.provider :aws do |aws, override|
        profile = Aws::SharedCredentials.new(:profile_name => "default")
        aws.access_key_id = profile.credentials.access_key_id
        aws.secret_access_key = profile.credentials.secret_access_key

        override.ssh.private_key_path = asset['private_key_path']
        aws.keypair_name = asset['aws_keypair_name']
        aws.region = asset["region"]

        aws.elastic_ip = true
        aws.associate_public_ip = true
        aws.ssh_host_attribute = :public_ip_address

        aws.ami = node["ami"]
        node_config.vm.synced_folder ".", "/vagrantshared" , type: "rsync"

        if asset["subnet_id"]
          aws.subnet_id = asset["subnet_id"]
        end


        # VPC's can have specific security groups
        if asset['secgroup_name']
          # puts "Debugging:: Sec Group: " + node['secgroup_name'].join(",")
          aws.security_groups = asset['secgroup_name']
        end

        # If default user defined otherwise ec2-user
        if node["user"]
          override.ssh.username = node["user"]
        else
          override.ssh.username = "ec2-user"
        end

        if node["type"]
          aws.instance_type = node["type"]
        else
          aws.instance_type = "t2.micro"
        end
        if node["isWin"]
          node_config.vm.communicator = "winrm"
        end
        aws.tags = {
            'Name' => node["name"],
        }
        # unless node['userData'].nil?
        #   aws.user_data = File.read(node['userData'])
        # end
      end

      node_config.vm.post_up_message = "System has provisioned successfully -- please validate the boxes ~cappetta"
    end


  end
end
