# -*- mode: ruby -*-
# vi: set ft=ruby :

# ref_url: https://github.com/DevNIX/Vagrant-dependency-manager
# require File.dirname(__FILE__)+"/vagrant_customizations/dependency_manager"
# check_plugins ["vagrant-docker-compose", "vagrant-awsinfo", "vagrant-docker-login", "vagrant-aws", "vagrant-share", "vagrant-winrm-syncedfolders"]

require 'yaml'
network = YAML.load_file("./yaml/aws.yaml")
assets = YAML.load_file("./yaml/assets.yaml")

Vagrant.configure("2") do |config|
  config.vm.box = "dummy"
  config.vm.box_url = "https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box"

  assets.each do |asset|
    config.vm.define asset["name"] do |node_config|
      node_config.vm.provider :aws do |aws, override|
        profile = Aws::SharedCredentials.new(:profile_name => "us-east-1")
        aws.access_key_id = profile.credentials.access_key_id
        aws.secret_access_key = profile.credentials.secret_access_key

        override.ssh.private_key_path = network['private_key_path']
        aws.keypair_name = network['aws_keypair_name']
        aws.region = network["region"]

        # aws.elastic_ip = true
        aws.associate_public_ip = true
        aws.ssh_host_attribute = :public_ip_address

        aws.ami = asset["ami"]

        # VPC's, subnets & security groups are required
        if network["subnet_id"]
          aws.subnet_id = network["subnet_id"]
        end

        if network['secgroup_id']
          aws.security_groups = network['secgroup_id']
        end

        # If default user defined otherwise ec2-user
        if asset["user"]
          override.ssh.username = asset["user"]
        else
          override.ssh.username = "ec2-user"
        end

        if asset["type"]
          aws.instance_type = asset["type"]
        else
          aws.instance_type = "t2.micro"
        end
        if asset["isWin"]
          node_config.vm.communicator = "winrm"
          type = "nfs"
        else
          type = "rsync"
        end
        node_config.vm.synced_folder ".", "/vagrantshared" , type: type
        aws.tags = {
            'Name' => asset["name"],
        }

        if asset["expand"]
          aws.block_device_mapping = [{ 'DeviceName' => '/dev/sda1', 'Ebs.VolumeSize' => 50  }]
        end

        unless asset['userData'].nil?
          aws.user_data = File.read(asset['userData'])
        end
      end

      node_config.vm.post_up_message = "System has provisioned successfully -- please validate the boxes ~cappetta"
    end


  end
end
