describe aws_ec2_instance(name: "ami_ms3_2k12") do it { should exist }; it { should be_running }; end
describe aws_ec2_instance(name: "cr_bulldog") do it { should exist }; it { should be_running }; end
describe aws_ec2_instance(name: "cr_fristileaks") do it { should exist }; it { should be_running }; end
describe aws_ec2_instance(name: "cr_hackinos") do it { should exist }; it { should be_running }; end
describe aws_ec2_instance(name: "cr_mrrobot") do it { should exist }; it { should be_running }; end
describe aws_ec2_instance(name: "cr_ms3_2k8") do it { should exist }; it { should be_running }; end
describe aws_ec2_instance(name: "cr_ms3_nix") do it { should exist }; it { should be_running }; end
describe aws_ec2_instance(name: "cr_myhouse7") do it { should exist }; it { should be_running }; end
describe aws_ec2_instance(name: "cr_sickos") do it { should exist }; it { should be_running }; end
describe aws_ec2_instance(name: "cr_skytower") do it { should exist }; it { should be_running }; end
describe aws_ec2_instance(name: "cr_stapler") do it { should exist }; it { should be_running }; end
describe aws_ec2_instance(name: "cr_vulnos") do it { should exist }; it { should be_running }; end
describe aws_ec2_instance(name: "cuckoo-host-ubuntu-1604") do it { should exist }; it { should be_running }; end
describe aws_ec2_instance(name: "cuckoo_guest") do it { should exist }; it { should be_running }; end
describe aws_ec2_instance(name: "defender_win2k10") do it { should exist }; it { should be_running }; end
describe aws_ec2_instance(name: "docker") do it { should exist }; it { should be_running }; end
describe aws_ec2_instance(name: "flarevm-win7") do it { should exist }; it { should be_running }; end
describe aws_ec2_instance(name: "kali") do it { should exist }; it { should be_running }; end
describe aws_ec2_instance(name: "nessus") do it { should exist }; it { should be_running }; end
describe aws_ec2_instance(name: "nnm") do it { should exist }; it { should be_running }; end
describe aws_ec2_instance(name: "pT10_commando") do it { should exist }; it { should be_running }; end
describe aws_ec2_instance(name: "r7vm") do it { should exist }; it { should be_running }; end
describe aws_ec2_instance(name: "sc") do it { should exist }; it { should be_running }; end
describe aws_ec2_instance(name: "was") do it { should exist }; it { should be_running }; end
describe aws_ec2_instance(name: "win2003") do it { should exist }; it { should be_running }; end
describe aws_ec2_instance(name: "win2008") do it { should exist }; it { should be_running }; end
describe aws_ec2_instance(name: "win2012") do it { should exist }; it { should be_running }; end
describe aws_ec2_instance(name: "win2012_RTM") do it { should exist }; it { should be_running }; end
describe aws_ec2_instance(name: "win2016") do it { should exist }; it { should be_running }; end
describe aws_ec2_instance(name: "win2019") do it { should exist }; it { should be_running }; end
describe aws_ec2_instance(name: "win7") do it { should exist }; it { should be_running }; end
describe aws_ec2_instance(name: "win8") do it { should exist }; it { should be_running }; end