describe aws_ec2_instance(name: "CyberRange-FBCTF-0") do it { should exist }; end
describe aws_ec2_instance(name: "CyberRange-MetaSploitable_3_win2k12-0") do it { should exist }; end
describe aws_ec2_instance(name: "CyberRange-MetaSploitable_3_win2k8-0") do it { should exist }; end
describe aws_ec2_instance(name: "CyberRange-MrRobot-0") do it { should exist }; end
describe aws_ec2_instance(name: "CyberRange-Sickos-0") do it { should exist }; end
describe aws_ec2_instance(name: "CyberRange-Skytower-0") do it { should exist }; end
describe aws_ec2_instance(name: "CyberRange-Stapler-0") do it { should exist }; end
describe aws_ec2_instance(name: "CyberRange-Tpot-0") do it { should exist }; end
describe aws_ec2_instance(name: "CyberRange-Vulnos-0") do it { should exist }; end
describe aws_ec2_instance(name: "CyberRange-bulldog-0") do it { should exist }; end
describe aws_ec2_instance(name: "CyberRange-commando-pT16-0") do it { should exist }; end
describe aws_ec2_instance(name: "CyberRange-commando-v2-0") do it { should exist }; end
describe aws_ec2_instance(name: "CyberRange-cuckoo-guest-win7-0") do it { should exist }; end
describe aws_ec2_instance(name: "CyberRange-cuckoo-host-ubuntu1804") do it { should exist }; end
describe aws_ec2_instance(name: "CyberRange-detection_lab_logger") do it { should exist }; end
describe aws_ec2_instance(name: "CyberRange-docker-via-cloudinit-0") do it { should exist }; end
describe aws_ec2_instance(name: "CyberRange-flarevm-win7-0") do it { should exist }; end
describe aws_ec2_instance(name: "CyberRange-fristileaks-0") do it { should exist }; end
describe aws_ec2_instance(name: "CyberRange-hackinos-0") do it { should exist }; end
describe aws_ec2_instance(name: "CyberRange-kali-linux-0") do it { should exist }; end
describe aws_ec2_instance(name: "CyberRange-ms3_nix-0") do it { should exist }; end
describe aws_ec2_instance(name: "CyberRange-myhouse7-0") do it { should exist }; end
describe aws_ec2_instance(name: "CyberRange-nessus-0") do it { should exist }; end
describe aws_ec2_instance(name: "CyberRange-nnm-0") do it { should exist }; end
describe aws_ec2_instance(name: "CyberRange-r7-0") do it { should exist }; end
describe aws_ec2_instance(name: "CyberRange-remnux-6.0") do it { should exist }; end
describe aws_ec2_instance(name: "CyberRange-sc-0") do it { should exist }; end
describe aws_ec2_instance(name: "CyberRange-win2008-0") do it { should exist }; end
describe aws_ec2_instance(name: "CyberRange-win2012-0") do it { should exist }; end
describe aws_ec2_instance(name: "CyberRange-win2012_RTM-0") do it { should exist }; end
describe aws_ec2_instance(name: "CyberRange-win2016-0") do it { should exist }; end
describe aws_ec2_instance(name: "CyberRange-win2019-0") do it { should exist }; end
describe aws_ec2_instance(name: "CyberRange-win2k10-0") do it { should exist }; end
describe aws_ec2_instance(name: "CyberRange-win7-0") do it { should exist }; end
describe aws_ec2_instance(name: "CyberRange-win8-0") do it { should exist }; end
describe aws_ec2_instance(name: "dc.windomain.local") do it { should exist }; end
describe aws_ec2_instance(name: "wef.windomain.local") do it { should exist }; end
describe aws_ec2_instance(name: "win10.windomain.local") do it { should exist }; end
