describe aws_ec2_instance(name: "win2012_RTM-0") do it { should exist }; end
describe aws_ec2_instance(name: "hackinos-0") do it { should exist }; end
describe aws_ec2_instance(name: "Stapler-0") do it { should exist }; end
describe aws_ec2_instance(name: "docker-web-apps-0") do it { should exist }; end
describe aws_ec2_instance(name: "myhouse7-0") do it { should exist }; end
describe aws_ec2_instance(name: "Skytower-0") do it { should exist }; end
describe aws_ec2_instance(name: "win2008-0") do it { should exist }; end
describe aws_ec2_instance(name: "win2003-0") do it { should exist }; end
describe aws_ec2_instance(name: "win2019-0") do it { should exist }; end
describe aws_ec2_instance(name: "win7-0") do it { should exist }; end
describe aws_ec2_instance(name: "MetaSploitable_3_win2k12-0") do it { should exist }; end
describe aws_ec2_instance(name: "win2k10-0") do it { should exist }; end
describe aws_ec2_instance(name: "ms3_nix-0") do it { should exist }; end
describe aws_ec2_instance(name: "MrRobot-0") do it { should exist }; end
describe aws_ec2_instance(name: "win8-0") do it { should exist }; end
describe aws_ec2_instance(name: "bulldog-0") do it { should exist }; end
describe aws_ec2_instance(name: "Vulnos-0") do it { should exist }; end
describe aws_ec2_instance(name: "win2012-0") do it { should exist }; end
describe aws_ec2_instance(name: "fristileaks-0") do it { should exist }; end
describe aws_ec2_instance(name: "Sickos-0") do it { should exist }; end
