describe aws_ec2_instance(name: "FBCTF-0") do it { should exist }; end
describe aws_ec2_instance(name: "MetaSploitable_3_win2k12-0") do it { should exist }; end
describe aws_ec2_instance(name: "MetaSploitable_3_win2k8-0") do it { should exist }; end
describe aws_ec2_instance(name: "MrRobot-0") do it { should exist }; end
describe aws_ec2_instance(name: "Sickos-0") do it { should exist }; end
describe aws_ec2_instance(name: "Skytower-0") do it { should exist }; end
describe aws_ec2_instance(name: "Stapler-0") do it { should exist }; end
describe aws_ec2_instance(name: "Tpot-0") do it { should exist }; end
describe aws_ec2_instance(name: "Vulnos-0") do it { should exist }; end
describe aws_ec2_instance(name: "bulldog-0") do it { should exist }; end
describe aws_ec2_instance(name: "commando-pT16-0") do it { should exist }; end
describe aws_ec2_instance(name: "commando-v2-0") do it { should exist }; end
describe aws_ec2_instance(name: "cuckoo-guest-win7-0") do it { should exist }; end
describe aws_ec2_instance(name: "cuckoo-host-ubuntu1804") do it { should exist }; end
describe aws_ec2_instance(name: "detection_lab_logger") do it { should exist }; end
describe aws_ec2_instance(name: "docker-via-cloudinit-0") do it { should exist }; end
describe aws_ec2_instance(name: "flarevm-win7-0") do it { should exist }; end
describe aws_ec2_instance(name: "fristileaks-0") do it { should exist }; end
describe aws_ec2_instance(name: "hackinos-0") do it { should exist }; end
describe aws_ec2_instance(name: "kali-linux-0") do it { should exist }; end
describe aws_ec2_instance(name: "ms3_nix-0") do it { should exist }; end
describe aws_ec2_instance(name: "myhouse7-0") do it { should exist }; end
describe aws_ec2_instance(name: "nessus-0") do it { should exist }; end
describe aws_ec2_instance(name: "nnm-0") do it { should exist }; end
describe aws_ec2_instance(name: "r7-0") do it { should exist }; end
describe aws_ec2_instance(name: "remnux-6.0") do it { should exist }; end
describe aws_ec2_instance(name: "sc-0") do it { should exist }; end
describe aws_ec2_instance(name: "win2008-0") do it { should exist }; end
describe aws_ec2_instance(name: "win2012-0") do it { should exist }; end
describe aws_ec2_instance(name: "win2012_RTM-0") do it { should exist }; end
describe aws_ec2_instance(name: "win2016-0") do it { should exist }; end
describe aws_ec2_instance(name: "win2019-0") do it { should exist }; end
describe aws_ec2_instance(name: "win2k10-0") do it { should exist }; end
describe aws_ec2_instance(name: "win7-0") do it { should exist }; end
describe aws_ec2_instance(name: "win8-0") do it { should exist }; end
describe aws_ec2_instance(name: "dc.windomain.local") do it { should exist }; end
describe aws_ec2_instance(name: "wef.windomain.local") do it { should exist }; end
describe aws_ec2_instance(name: "win10.windomain.local") do it { should exist }; end
