#!/usr/bin/env bash

git clone https://github.com/cappetta/CyberRange.git
git clone https://github.com/clong/DetectionLab.git
git clone https://github.com/1N3/IntruderPayloads.git
git clone https://github.com/cappetta/SecDevOps-Toolkit.git
git clone https://github.com/Netflix-Skunkworks/aws-credential-compromise-detection
git clone https://github.com/rebuy-de/aws-nuke.git
git clone https://github.com/28mm/blast-radius.git
git clone https://github.com/twbs/bootstrap.git
git clone https://github.com/cappetta/circleci_terraform.git
git clone https://github.com/RhinoSecurityLabs/cloudgoat
git clone https://github.com/duo-labs/cloudmapper.git
git clone https://github.com/rapid7/metasploitable3.git
git clone https://github.com/joefitzgerald/packer-windows.git
git clone https://github.com/RhinoSecurityLabs/pacu.git
git clone https://github.com/phzietsman/security-monkey-terraform.git
git clone https://github.com/Netflix/security_monkey.git
git clone https://github.com/pirate/sites-using-cloudflare.git
git clone https://github.com/DanMcInerney/net-creds.git
git clone https://github.com/codingo/Reconnoitre.git
git clone https://github.com/qbob1/shell_generator.sh.git
git clone https://github.com/shizzz477/msploitego.git
git clone https://github.com/jesusprubio/awesome-nodejs-pentest.git
git clone https://github.com/RhinoSecurityLabs/cloudgoat.git
git clone https://github.com/dowjones/hammer.git
git clone https://github.com/OWASP/joomscan.git
git clone https://github.com/scottslowe/learning-tools.git
git clone https://github.com/varchashva/LetsMapYourNetwork.git
git clone https://github.com/JohnTroony/php-webshells
git clone https://github.com/AdrianVollmer/PowerHub.git
git clone https://github.com/PowerShellMafia/PowerSploit.git
git clone https://github.com/Exploit-install/snmpwn.git
git clone https://github.com/vulhub/vulhub.git
git clone https://github.com/nccgroup/ScoutSuite.git
git clone https://github.com/toniblyx/prowler.git
git clone https://github.com/tmobile/pacbot.git
git clone https://github.com/nozaq/terraform-aws-secure-baseline.git
git clone https://github.com/zricethezav/gitleaks.git
git clone https://github.com/toniblyx/my-arsenal-of-aws-security-tools.git
git clone https://github.com/cylance/CyBot